### ISSUE TITLE
Create a Policy for the Opf DS Community Meetup

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/operate-first-data-science-community#28]
We would want to create a policy for the Opf DS Community Meetup, that would allow the users to know what all data we would be recording like the meetups being recorded, the attendees data being recorded. 

We would also however ensure that the data is not posted publicly with the attendees' public information.

Acceptance Criteria - 
Policy document for Operate First Data Science Community Meetup

**Comment by chauhankaranraj** [comment]
Hey team, has anyone started working on this yet? If not, I'm happy to start a doc and anyone who'd like to contribute can collaborate there? wdyt?

**Comment by aakankshaduggal** [comment]
Sounds good @chauhankaranraj , I can work with you on this one.
