### ISSUE TITLE
EDA for the obfuscation data

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/operate-first-data-science-community#57]
Acceptance Criteria

- [ ] Create a jupyter notebook would :
1. fetch data for the meetup attendees from `opf-datacatalog` bucket
2. Small description of the data
3. What does the data frame look like?
4. Some EDA on this dataset

**Comment by suppathak** [comment]
@aakankshaduggal , If this issue still needs to be assigned to someone, I am interested to explore it. Lmk, if I can assign myself to it. Thanks!

**Comment by aakankshaduggal** [comment]
@suppathak 
Sure, feel free to assign yourself. Let me know if you need any help :)
