### ISSUE TITLE
Q1 Report of Operate First Data Science Community

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/operate-first-data-science-community#72]
Acceptance Criteria :

- [ ] A single page report summarizing everything
- [ ] Share & Publish this report publicly on Github/JupyterBook

**Comment by oindrillac** [comment]
Is being worked on somewhere? @aakankshaduggal I'd like to contribute to this report

**Comment by aakankshaduggal** [comment]
Thanks @oindrillac , here's a WIP [document](https://docs.google.com/document/d/1yI4pyYGLoHcYRcLLzKwcDpjeIyy1Z7jHCeenFFz5_LU/edit?usp=sharing).
