### ISSUE TITLE
Obfuscation Techniques

### ISSUE THREAD

**Issue by suppathak** [aicoe-aiops/operate-first-data-science-community#73]
## Please provide the following info about your topic submission

**Title** 
Obfuscation techniques applied to Operate-first meetup data

**Short Description**
Obfuscation techniques applied to Operate-first meetup data

**When would you like to present?**
TBD

**Presenter(s)**
Surya Prakash Pathak

**Additional Info**
@suppathak 

**Accepted**
- [x] Yes
- [ ] No

**Comment by aakankshaduggal** [comment]
closing this issue, since we are tracking this talk in #87
