### ISSUE TITLE
Update calendar invite

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/operate-first-data-science-community#89]
By looking at the calendar invite, it's not immediately clear to me whats the talk scheduled for the day and what this meetup is about. I would suggest including the Agenda in the calendar invite. 

Something like:

This meetup is hosted every two weeks.  The purpose of the meetup is to .....
Anybody who is interested in ...... is welcome to join.

**Upcoming Session and past meetups** - https://www.operate-first.cloud/data-science/operate-first-data-science-community/docs/content.md
**About the Meetup** - [https://www.operate-first.cloud/data-science/operate-first-data-science-community/docs/meetup-landing-page.md](https://www.google.com/url?q=https://www.operate-first.cloud/data-science/operate-first-data-science-community/docs/meetup-landing-page.md&sa=D&source=calendar&ust=1651001197873344&usg=AOvVaw0UlmTq7Hdd2F1cm639Ob0x)

**Comment by aakankshaduggal** [comment]
Thanks @oindrillac for pointing this out. I have put together a draft here. Please lmk if this looks okay and @MichaelClifford could you please add it to the invite :smile: 

----

The **Operate First Data Science Community Meetup** is a biweekly event, open to everyone interested in learning more about how various individuals, teams, and online communities are working towards democratizing the development of production-level AI.

This meetup aims to embrace the multi-disciplinary nature of the current state of AI operations and cloud infrastructure by covering technical topics relevant to data scientists, software engineers, DevOps professionals, and statisticians alike. And all in an open public forum.

**Upcoming Session and past meetups** - https://www.operate-first.cloud/data-science/operate-first-data-science-community/docs/content.md
**About the Meetup** - [https://www.operate-first.cloud/data-science/operate-first-data-science-community/docs/meetup-landing-page.md](https://www.google.com/url?q=https://www.operate-first.cloud/data-science/operate-first-data-science-community/docs/meetup-landing-page.md&sa=D&source=calendar&ust=1651001197873344&usg=AOvVaw0UlmTq7Hdd2F1cm639Ob0x)

Ways to Participate:
1. Join our meetup every other Tuesday @ 11:00 ET on [google meet](https://meet.google.com/eyb-yegj-gji).
2. Suggest topics/ present talks: https://github.com/aicoe-aiops/cloud-first-data-science-community/issues/new/choose
3. Slack: https://join.slack.com/t/operatefirst/shared_invite/zt-o2gn4wn8-O39g7sthTAuPCvaCNRnLww 
4. Mailing List: https://lists.operate-first.cloud/admin/lists/community.lists.operate-first.cloud/

**Comment by MichaelClifford** [comment]
Should we also take this opportunity to move the invite to the OPF calendar? I think it is currently on its own calendar that I manage. Who has admin access on the wider OPF calendar?

**Comment by aakankshaduggal** [comment]
@MichaelClifford and I, have updated our current calendar invite and also updated the op1st community calendar.

**Comment by oindrillac** [comment]
Seems like the invite is updated and is present on the OPF calendar as well! Thanks @aakankshaduggal @MichaelClifford. Closing this :)
